// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eflywjkwtmqllvuzdfnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbHl3amt3dG1xbGx2dXpkZm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTk0NzYsImV4cCI6MjA3MjgzNTQ3Nn0.EvCYpKg7tkhtB_bseHWRwv7Tz1UOCZuZ96k4F-U2_hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});